language: node_js
node_js: 8.11.4

deploy: 
  - 
    provider: script
    script: ./abc.sh
    skip_cleanup: true
    true: 
      branch: master
  - 
    provider: script
    script: ./def.sh
    skip_cleanup: true
    true: 
      branch: release

